# Generated by Django 3.1.2 on 2021-05-19 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('downvotes', models.ManyToManyField(blank=True, related_name='post_downvotes', to=settings.AUTH_USER_MODEL)),
                ('posted_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.community')),
                ('upvotes', models.ManyToManyField(blank=True, related_name='post_upvotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
