# Generated by Django 3.0.3 on 2020-10-28 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201028_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='scor',
            new_name='score',
        ),
    ]
