# Generated by Django 3.1.2 on 2021-05-18 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_post_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='title',
            new_name='name',
        ),
    ]
