# Generated by Django 3.1.2 on 2021-05-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210518_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='members',
        ),
        migrations.AddField(
            model_name='post',
            name='posted_to',
            field=models.ManyToManyField(blank=True, related_name='posted_to_community', to='blog.Community'),
        ),
    ]
